#!/usr/bin/expect
set timeout 10
set username "K1ose"
set password "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"

spawn git push
expect "Username*"
send "$username\n"
expect "Password*"
send "$password\n"
expect eof
